name: Rebuild debian-*.csv

on:
  schedule:
    # Every Saturday afternoon
    - cron: "0 15 * * 6"

jobs:
  update-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Rebuild
        timeout-minutes: 5
        run: |
          set -e
          git config user.name "Johan Gunnarsson"
          git config user.email "johan.gunnarsson@gmail.com"
          ./metascripts/rebuild-debian-csv
          git add debians-arm.csv debians-x86.csv
          if git commit -m "debians: Update Debian/Ubuntu versions"; then
            ./metascripts/rebuild-jekyll-boards
            git add -A docs
            if git commit -m "docs: Regenerate boards"; then
              git push origin
            fi
          fi
